package repositories

import (
	"U-235/models"
	"context"
	"database/sql"
	"errors"
	"fmt"
)

type UserRepository interface {
	UserRegistrationService(Name, email, passwordHashed string, ctx context.Context) (*models.User, error)
	UserLoginService(user models.UserLogin, ctx context.Context) error
}

type userRepo struct {
	db *sql.DB
}

func NewUserRepo(db *sql.DB) UserRepository {
	return &userRepo{
		db: db,
	}
}

func (u *userRepo) UserRegistrationService(name, email, passwordHashed string, ctx context.Context) (*models.User, error) {
	// Check if user already exists
	var existingUser models.User
	checkQuery := `SELECT id FROM users WHERE email = $1`
	err := u.db.QueryRowContext(ctx, checkQuery, email).Scan(&existingUser.Id)

	// If no error, user exists
	if err == nil {
		return nil, errors.New("user with this email already exists")
	}

	// If error is not "no rows", return the error
	if err != sql.ErrNoRows {
		return nil, fmt.Errorf("error checking existing user: %w", err)
	}

	// User doesn't exist, create new user
	// UUID will be auto-generated by the database
	var user models.User
	insertQuery := `INSERT INTO users (name, email, password) 
                    VALUES ($1, $2, $3) 
                    RETURNING id, name, email, created_at`

	err = u.db.QueryRowContext(
		ctx,
		insertQuery,
		name,
		email,
		passwordHashed,
	).Scan(&user.Id, &user.Name, &user.Email, &user.CreatedAt)

	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	return &user, nil
}

func (u userRepo) UserLoginService(user models.UserLogin, ctx context.Context) error {
	//TODO implement me
	panic("implement me")
}
